#!/bin/sh

RESOLV_CONF=/etc/resolv.conf

case "$1" in
deconfig)
	ifconfig "$interface" 0.0.0.0
	;;
bound|renew)
	ifconfig "$interface" "$ip" ${subnet:+netmask "$subnet"}

	if test -n "$router"; then
		route del default 2>/dev/null
		for r in $router; do
			route add default gw "$r" dev "$interface"
		done
	fi

	if test -n "$dns"; then
		echo -n > "$RESOLV_CONF"
		for d in $dns; do
			echo "nameserver $d" >> "$RESOLV_CONF"
		done
	fi
	;;
esac

exit 0
