arch all   1
arch piko  10

dest root /

option info_dir     /var/lib/opkg/info
option status_file  /var/lib/opkg/status
option lists_dir    /var/lib/opkg/lists
option cache_dir    /var/cache/opkg
option lock_file    /var/run/opkg.lock

option tmp_dir      /tmp
