null            root:root 666
zero            root:root 666
full            root:root 666
random          root:root 444
urandom         root:root 444
console         root:tty  600
ptmx            root:tty  666
tty             root:tty  666
tty[0-9]*       root:tty  660
vcs[0-9]*       root:tty  660
vcsa[0-9]*      root:tty  660
mmcblk0p1       root:root 660 */usr/sbin/sdcard
mmcblk[0-9].*   root:root 660
mtdblock[0-9]*  root:root 660

$MODALIAS=.*    root:root 660 @modprobe -b "$MODALIAS"

wlan0           root:root 660 @/etc/wifi-up.sh
