export TERM=linux
export HOME=/root
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
[ -r /etc/TZ ] && export TZ="$(cat /etc/TZ)"
[ -r /etc/zaurus-card.sh ] && . /etc/zaurus-card.sh
FPATH=/usr/share/zsh/5.9/functions:$FPATH
autoload -Uz compinit && compinit -u
autoload -Uz promptinit && promptinit
prompt redhat
HISTFILE=/root/.zsh_history
HISTSIZE=500
setopt hist_ignore_dups autocd
