#ifndef HOSTAP_CONFIG_H
#define HOSTAP_CONFIG_H

#define PRISM2_NO_PROCFS_DEBUG

#define HAVE_SET_MAC_ADDR
#define HAVE_TX_TIMEOUT
#define HAVE_MULTICAST
#define HAVE_CHANGE_MTU
#define HAVE_PRIVATE_IOCTL

#define PRISM2_VERSION "0.4.7 - 2005-11-20"

#define PRISM2_MAX_INTERRUPT_EVENTS 20

#ifdef PRISM2_BUS_MASTER

#define PRISM2_ENABLE_BEFORE_TX_BUS_MASTER

#endif 

#define PRISM2_DOWNLOAD_SUPPORT

#if !defined(PRISM2_DOWNLOAD_SUPPORT) && defined(CONFIG_HOSTAP_FIRMWARE)
#define PRISM2_DOWNLOAD_SUPPORT
#endif

#ifdef PRISM2_DOWNLOAD_SUPPORT

#endif 

#endif 
