--enable MTD
--enable MTD_BLOCK
--enable MTD_RAW_NAND
--enable MTD_NAND_SHARPSL
--enable MTD_SHARPSL_PARTS
--enable JFFS2_FS
--enable JFFS2_FS_WRITEBUFFER
--enable JFFS2_ZLIB
--enable JFFS2_RTIME
--disable MMC
--disable PCMCIA
--disable VFAT_FS
