--disable JFFS2_FS
--disable JFFS2_FS_WRITEBUFFER
--disable JFFS2_ZLIB
--disable JFFS2_LZO
--disable JFFS2_RTIME
--disable JFFS2_COMPRESSION_OPTIONS
--disable MTD_NAND_SHARPSL
--disable MTD_SHARPSL_PARTS
--disable MTD_RAW_NAND
--disable MTD_NAND_CORE
--disable MTD_CFI
--disable MTD_CFI_INTELEXT
--disable MTD_GEN_PROBE
--disable MTD_PHYSMAP
--disable MTD_COMPLEX_MAPPINGS
--disable MTD_BLOCK
--disable MTD_BLKDEVS
--disable MTD
--disable BLK_DEV_LOOP
--disable PCMCIA
--enable MMC
--enable MMC_BLOCK
--enable MMC_PXA
--enable FAT_FS
--enable VFAT_FS
--enable NLS
--enable NLS_CODEPAGE_437
--enable NLS_ISO8859_1
--set-val FAT_DEFAULT_CODEPAGE 437
--set-str FAT_DEFAULT_IOCHARSET iso8859-1
