name: clean workflow runs

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * 0"

permissions:
  actions: write

jobs:
  clean:
    name: clean
    runs-on: ubuntu-latest
    steps:
      - uses: dmvict/clean-workflow-runs@9b0fba98c68369add0884d6af67e6866578cbf98
        with:
          repo: ${{ github.repository }}
